apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    service: backend-feed
  name: backend-feed
spec:
  replicas: 1
  selector:
    matchLabels:
      service: backend-feed
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        service: backend-feed
    spec:
      containers:
        - env:
            - name: AWS_BUCKET
              value: $AWS_BUCKET
            - name: AWS_PROFILE
              value: $AWS_PROFILE
            - name: AWS_REGION
              value: $AWS_REGION
            - name: JWT_SECRET
              value: $JWT_SECRET
            - name: POSTGRESS_DB
              value: postgres
            - name: POSTGRESS_HOST
              value: $POSTGRESS_HOST
            - name: POSTGRESS_PASSWORD
              value: $POSTGRESS_PASSWORD
            - name: POSTGRESS_USERNAME
              value: $POSTGRESS_USERNAME
            - name: URL
              value: http://localhost:8100
          image: sanyamj/udagram-restfeed-api
          imagePullPolicy: IfNotPresent
          name: udagram-feed-api
          resources: {}
          volumeMounts:
            - mountPath: /root/.aws
              name: backend-secret
      restartPolicy: Always
      serviceAccountName: ""
      volumes:
        - name: backend-secret
          persistentVolumeClaim:
            claimName: backend-secret
status: {}
